options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$BUILD_ID',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$BUILD_ID'
      ]

  # Step 3: Create a new instance template using this build’s ID
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instance-templates',
        'create-with-container',
        'my-app-template-$BUILD_ID',
        '--machine-type=e2-medium',
        '--boot-disk-size=20GB',
        '--container-image=asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$BUILD_ID'
      ]

  # Step 4: Update MIG with rolling update
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instance-groups',
        'managed',
        'rolling-action',
        'start-update',
        'my-app-mig',
        '--version=template=my-app-template-$BUILD_ID',
        '--zone=us-central1-c'
      ]

images:
  - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$BUILD_ID'

timeout: '1200s'
