steps:
# Step 0: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/artifact-repo/simple-web-app:${COMMIT_SHA}'
    - '.'

# Step 1: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/artifact-repo/simple-web-app:${COMMIT_SHA}'

# Step 2: Deploy to GCP (instance template + MIG)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod +x deploy.sh
      ./deploy.sh

# Optional: Logs only in Cloud Logging (avoids build bucket requirement)
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ZONE: "asia-south1-a"
  _MIG_NAME: "my-app-mig"
  _PROJECT_ID: "psyched-option-421700"
  COMMIT_SHA: $SHORT_SHA
