steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:latest']

images:
  - 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:latest'
