steps:
# Step 0: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA'
    - .
  id: Build

# Step 1: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA'
  id: Push

# Step 2: Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod +x deploy.sh
      ./deploy.sh
  id: Deploy

substitutions:
  _ZONE: "asia-south1-a"
  _MIG_NAME: "my-app-mig"
  _PROJECT_ID: "psyched-option-421700"

options:
  logging: CLOUD_LOGGING_ONLY
