options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 0: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA
    - .
    
# Step 1: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA

# Step 2: Deploy to GCP
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod +x deploy.sh
      ./deploy.sh $COMMIT_SHA

substitutions:
  _MIG_NAME: "my-app-green"
  _TEMPLATE_NAME_PREFIX: "my-app-template"
  _ZONE: "asia-south1-a"

timeout: 1200s
