options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest',
      '.'
    ]

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
    ]

# Step 3: Update MIG
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - './update-mig.sh'

images:
  - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
