gcloud compute instance-templates create $TEMPLATE_NAME \
  --machine-type=n1-standard-1 \
  --image-family=debian-12 \
  --image-project=debian-cloud \
  --metadata-from-file=startup-script=startup.sh
