options:
  logging: CLOUD_LOGGING_ONLY


steps:
# Step 0: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA'
    - '.'

# Step 1: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:$COMMIT_SHA'

# Step 2: Deploy to MIG using deploy.sh
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - './deploy.sh'
  env:
    - 'COMMIT_SHA=$COMMIT_SHA'

substitutions:
  _ZONE: 'us-central1-c'
  _MIG_NAME: 'my-app'
  _PROJECT_ID: 'psyched-option-421700'

timeout: '1200s'
