options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
      ]

  # Step 3: Create new instance template with startup script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-templates create my-template \
          --machine-type=e2-small \
          --tags=http-server,https-server \
          --metadata-from-file=startup-script=script.sh \
          --quiet

  # Step 4: Rolling update MIG to new template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-groups managed rolling-action start-update my-app \
          --version=template=my-template \
          --region=us-central1 \
          --type=proactive \
          --max-surge=1 \
          --max-unavailable=0 \
          --quiet

  # Step 5: Delete old instance template (single command in bash)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        old_template=$(gcloud compute instance-templates list \
          --filter="name!=my-template" \
          --format="value(name)" | head -n 1)
        if [ -n "$old_template" ]; then
          gcloud compute instance-templates delete "$old_template" --quiet
        fi

images:
  - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
