options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
      ]

  # Step 3: Create template, rolling update, cleanup — all inside one single-quoted bash string
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - '
        TEMPLATE_NAME=my-template-$(date +%s)
        echo "Creating instance template: $TEMPLATE_NAME"
        gcloud compute instance-templates create "$TEMPLATE_NAME" \
          --machine-type=e2-small \
          --tags=http-server,https-server \
          --metadata-from-file=startup-script=script.sh \
          --quiet

        echo "Rolling update MIG my-app to template: $TEMPLATE_NAME"
        gcloud compute instance-groups managed rolling-action start-update my-app \
          --version=template="$TEMPLATE_NAME" \
          --zone=us-central1-c \
          --type=proactive \
          --max-surge=1 \
          --max-unavailable=0 \
          --quiet

        # Cleanup old templates (keep last 3)
        templates=$(gcloud compute instance-templates list \
          --filter="name~'"'"'my-template-'"'"'" \
          --sort-by=~creationTimestamp \
          --format="value(name)" | tail -n +4)
        for t in $templates; do
          echo "Deleting old template: $t"
          gcloud compute instance-templates delete "$t" --quiet
        done
      '

images:
  - 'asia-south1-docker.pkg.dev/psyched-option-421700/artifact-repo/simple-web-app:latest'
