steps:
# Step 0: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/artifact-repo/simple-web-app:${SHORT_SHA}'
    - '.'

# Step 1: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/${PROJECT_ID}/artifact-repo/simple-web-app:${SHORT_SHA}'

# Step 2: Deploy to MIG
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      chmod +x deploy.sh
      COMMIT_SHA=${SHORT_SHA} MIG_NAME=${_MIG_NAME} ZONE=${_ZONE} PROJECT_ID=${PROJECT_ID} ./deploy.sh

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ZONE: "asia-south1-a"
  _MIG_NAME: "my-app-mig"
